# Generated by Django 3.2.7 on 2021-09-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog',
            table='dogs',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='owner',
        ),
    ]
